pipeline {

   agent {
        node {
            label 'unix'
        }
   }



   stages {
        stage('Compile/Test/Install') {
            steps {
                withMaven( maven: 'Maven 3.3.9') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Archive artifacts') {
            steps {
                archiveArtifacts artifacts: '**/*.jar',  allowEmptyArchive: true
                archiveArtifacts artifacts: 'target/surefire-reports/*.xml',  allowEmptyArchive: true
            }
        }
   }

   post {
        failure {
            echo 'I will always say Hello again!'
        }
   }
}
